# Artificial Neural Network
The purpose of the following notebook is to provide a simple implementation to get hands on experience, and thus hopefully also a deeper understanding of the backwards error propagation approach to neural network. The task for the network is to classify iris set of data from [UCI](https://archive.ics.uci.edu/ml/datasets/Iris), and will thereby be a form of supervised learning.

## 1. Setting up the artificial network class [WIP]

In [35]:
import numpy as np
import pandas as pd

In [30]:
def activation_function(x):
    """Calculates the activation of a node give an input

    Args:
        x (integer: Scalar) :  Number representing the sum of the input to the give node
    """
    return (1 + np.e**-x)**-1

activation = np.vectorize(activation_function)

In [31]:
class ANN:
    def __init__(self, features, hidden_layers, outputs):
        """
        Takes as input
            hidden_layers : 1d array with number of neurons to include in each of the hidden layers
            features : int representing the number of features of the data set - corresponds to the first (input) layer
            outputs : int representing the number of possible outputs - and thereby number of nodes in the final (output) layer
        """
        
        # Meta data
        self.num_layers = len(hidden_layers) + 2
        self.num_outputs = outputs
        self.num_features = features
        
        combined_layers  = np.array([features] + hidden_layers + [outputs])

        # Setting up the layers
        self.layers = []
        for num in combined_layers:
            self.layers.append([0 for _ in range(num)])

        # Setting up weights
        self.weights = []
        for i in range(len(combined_layers)-1):
            self.weights.append(np.random.rand(combined_layers[i], combined_layers[i+1]))
    
    def forward_pass(self, sample): 
        """Fixes the neural network to a sample and generates the prediction at the output layer

        Args:
            sample (ndarray): Array of floats which represents the value of the input sample
        """
        self.layers[0] = sample

        # Iterate through each layer and calculate activation based on 
        for i in range(1, self.num_layers):
            # Fetch the activation and weight of the previous layers
            prev_activation = self.layers[i-1]
            weights = self.weights[i-1]

            # Calculate inputs of the current nodes based on activation of previous and weights between them
            inputs = np.sum(weights * prev_activation[:, np.newaxis], axis = 0)

            # Update current layer with activation of inputs
            self.layers[i] = activation(inputs)

    def predict(self, sample):
        """Predicts the label of a sample x

        Args:
            sample (ndarray): Array of integers which represents the first input layer of the network

        Returns:
            ndarray: Array of floats which represent the confidences of the classification for each category of the output
        """
        self.forward_pass(sample)
        return self.layers[-1]

    def backprops_error(self, prediction, solution): 
        """Compares a prediction to a solution and calculates the error between the layer and the expected values

        Args:
            prediction (ndarray): Prediction, output of the network for some sample x
            solution (ndarray): The solution to the sample fetched from the dataset
        """
        pass


## Preprocessing data
The data is loaded from `./data/iris.data` and utilizes `pandas` to preprocess it. This includes splitting the attributes and the labels, and converting the categorical label to integers. 

In [93]:
# Loading from file
df = pd.read_csv('./data/iris.data', names=['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'label'])
y = df['label']
x = df.drop(['label'], axis=1)

In [94]:
# Converting labels from string to integers representing categories
uniques = y.unique()
label_map = {i: uniques[i] for i in range(len(uniques))}
y.replace(uniques, [i for i in range(len(uniques))], inplace = True)

## Setting up network and making predictions [WIP]
With the data loaded, the model is ready to be set up and make predictions based on the provided samples from the dataset. 

In [101]:
# Setting up network based on metadata
model_hidden_layers = [10, 6]

ann = ANN(len(x.columns), model_hidden_layers, len(uniques))

In [102]:
# Creating arrays with solutions for easier error calculation
solutions = []

for _, solution in y.items():
    
    solutions.append([1 if i == solution else 0 for i in range(len(uniques))])

In [103]:
# Making predictions for each sample and printing error terms
predictions = []

for idx, sample in x.iterrows():
    pred = ann.predict(sample.to_numpy())

    print(solutions[idx] - pred)


[ 0.13926147 -0.96625076 -0.93710438]
[ 0.13931469 -0.96622891 -0.93707086]
[ 0.13931918 -0.96622727 -0.93706847]
[ 0.13930458 -0.96623295 -0.93707686]
[ 0.13925705 -0.96625258 -0.93710717]
[ 0.1391824  -0.96628267 -0.93715312]
[ 0.13927957 -0.96624326 -0.93709278]
[ 0.13926096 -0.96625083 -0.93710436]
[ 0.13935215 -0.96621357 -0.9370473 ]
[ 0.13930177 -0.9662342  -0.93707886]
[ 0.13922602 -0.96626515 -0.9371264 ]
[ 0.13925672 -0.96625246 -0.93710671]
[ 0.13933177 -0.96622205 -0.93706039]
[ 0.13941795 -0.96618734 -0.93700776]
[ 0.13922758 -0.96626488 -0.93712634]
[ 0.1391663  -0.96628946 -0.9371638 ]
[ 0.13921733 -0.96626875 -0.93713208]
[ 0.13925209 -0.96625449 -0.93711007]
[ 0.13918739 -0.96628068 -0.9371501 ]
[ 0.13921994 -0.96626756 -0.93713005]
[ 0.13922612 -0.96626485 -0.93712571]
[ 0.13921886 -0.96626791 -0.93713054]
[ 0.13933117 -0.96622291 -0.93706221]
[ 0.13921917 -0.96626744 -0.93712956]
[ 0.13922557 -0.96626491 -0.93712554]
[ 0.13928248 -0.96624183 -0.93709038]
[ 0.13923253